### ISSUE TITLE
Digital Ocean Deployment

### ISSUE THREAD

**Issue by drewzamcp** [drewzamcp/pdm_wbdesigner#46]
Problem Statement:

Unable to get Uvicorn working on Ubuntu 20.4 Droplet deployed on Digital Ocean. Able to replicate it from within virtual env running locally so it's not an Ubuntu issue.

Issue: 

When starting the server using `uvicorn pdm_project_one.main:main`, it gets itself into a `uvloop` error

Full stack trace of the error below

```
(pdm_one_3.9.4) ➜  pdm_project_one git:(do_deploy) uvicorn pdm_project_one.main:main
INFO:     Started server process [42910]
INFO:     Waiting for application startup.
Traceback (most recent call last):
  File "/Users/azwerd/.pyenv/versions/pdm_one_3.9.4/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/Users/azwerd/.pyenv/versions/3.9.4/envs/pdm_one_3.9.4/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/azwerd/.pyenv/versions/3.9.4/envs/pdm_one_3.9.4/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/azwerd/.pyenv/versions/3.9.4/envs/pdm_one_3.9.4/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/azwerd/.pyenv/versions/3.9.4/envs/pdm_one_3.9.4/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/azwerd/.pyenv/versions/3.9.4/envs/pdm_one_3.9.4/lib/python3.9/site-packages/uvicorn/main.py", line 362, in main
    run(**kwargs)
  File "/Users/azwerd/.pyenv/versions/3.9.4/envs/pdm_one_3.9.4/lib/python3.9/site-packages/uvicorn/main.py", line 386, in run
    server.run()
  File "/Users/azwerd/.pyenv/versions/3.9.4/envs/pdm_one_3.9.4/lib/python3.9/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1494, in uvloop.loop.Loop.run_until_complete
  File "/Users/azwerd/.pyenv/versions/3.9.4/envs/pdm_one_3.9.4/lib/python3.9/site-packages/uvicorn/server.py", line 56, in serve
    config.load()
  File "/Users/azwerd/.pyenv/versions/3.9.4/envs/pdm_one_3.9.4/lib/python3.9/site-packages/uvicorn/config.py", line 314, in load
    self.loaded_app = self.loaded_app()
  File "./pdm_project_one/main.py", line 14, in main
    uvicorn.run(app)
  File "/Users/azwerd/.pyenv/versions/3.9.4/envs/pdm_one_3.9.4/lib/python3.9/site-packages/uvicorn/main.py", line 386, in run
    server.run()
  File "/Users/azwerd/.pyenv/versions/3.9.4/envs/pdm_one_3.9.4/lib/python3.9/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1488, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1481, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1370, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 511, in uvloop.loop.Loop._run
RuntimeError: this event loop is already running.
```

**Comment by mikeabrahamsen** [comment]
What is error message you run into when you execute the gunicorn command?

**Comment by drewzamcp** [comment]
I'm just getting my environment setup again quickly. Had to replace my notebook this week. 

I'll get setup again and share the error message here.

**Comment by drewzamcp** [comment]
`unicorn` should pick this config up to run the server. [gunicorn.conf.py](https://github.com/drewzamcp/pdm_wbdesigner/blob/master/pdm_project_one/gunicorn.conf.py)

**Comment by drewzamcp** [comment]
weird thing is, when I run it from the command line within the application directory it works perfectly.
```
poetry run python main.py
INFO:     Started server process [43741]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
```

**Comment by bbelderbos** [comment]
@drewzamcp I thought the app was working end-to-end? Are you still getting `RuntimeError: this event loop is already running.` then? If so I might set this up on DO quickly to see if I can reproduce it ...

**Comment by drewzamcp** [comment]
@bbelderbos I can start it manually on DO and leave it running but can't get it running as a service. 

## This works:
within the project directory I can run it using `python main.py `and it starts perfectly. 

## This doesn't work:
`uvicorn uvicorn pdm_project_one.main:main`

**Comment by bbelderbos** [comment]
Can reproduce that locally now, let's fix it ...

**Comment by drewzamcp** [comment]
I'll get this live this evening.

**Comment by bbelderbos** [comment]
I got it working now, see https://github.com/drewzamcp/pdm_wbdesigner/pull/50/files (and commit messages)

HTH
Bob

**Comment by timf-bonobos** [comment]
@drewzamcp  did you manage to get this up and running on DO? if not I would be more than willing to spend a few hours trying to get it stood up on my DO instance

**Comment by bbelderbos** [comment]
@drewzamcp running `poetry run uvicorn  pdm_project_one.main:configure` instead of `poetry run uvicorn  pdm_project_one.main:main` should have resolved the error, can you confirm please?

**Comment by drewzamcp** [comment]
@timf-bonobos Thanks Tim. Sorry it's taken a while to get back to you. I've been head down finishing off PDM project 2 which I needed to get handed in. If you have some time, I'd really appreciate you trying to get this setup on your DO environment. 
- Bob's changes have worked to resolve the uvicorn loop issue. 
- I think I messed up my nginx config which may be causing some grief. 
- I've got some time now so will start looking at this again.
